group :jekyll_plugins do
source 'https://rubygems.org'
#  gem "jekyll", "~> 3.8"
  gem "jekyll-default-layout", "~> 0.1.4"
  gem "jekyll-gist", "~> 1.5"
  gem "jekyll-github-metadata", "~> 2.12"
  gem "jekyll-include-cache", "~> 0.1"
  gem "jemoji", "~> 0.11"
end